services:
  socks5-proxy:
    build: .
    container_name: socks5-proxy
    network_mode: host
    environment:
      SOCKS5_CONFIG: /app/config/.env
    volumes:
      - ./config:/app/config
    restart: unless-stopped
