#!/bin/sh
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Paths
CONFIG_DIR="config"
ENV_FILE="${CONFIG_DIR}/.env"
ENV_EXAMPLE="${CONFIG_DIR}/.env.example"
ROOT_ENV_FILE=".env"

# Function to extract value from key=value file
get_value() {
    local file="$1"
    local key="$2"
    grep -E "^${key}=" "$file" 2>/dev/null | cut -d'=' -f2- | tr -d '\r' || echo ""
}

# Generate config/.env if missing
if [ ! -f "$ENV_FILE" ] && [ -f "$ENV_EXAMPLE" ]; then
    echo -e "${YELLOW}Config file $ENV_FILE not found, generating from $ENV_EXAMPLE...${NC}"
    ./scripts/generate-env.sh "$ENV_EXAMPLE" "$ENV_FILE"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to generate $ENV_FILE${NC}"
        exit 1
    fi
fi

# Determine which source file to use
SOURCE_FILE=""
if [ -f "$ENV_FILE" ]; then
    SOURCE_FILE="$ENV_FILE"
    echo -e "${GREEN}Using existing config: $ENV_FILE${NC}"
elif [ -f "$ENV_EXAMPLE" ]; then
    SOURCE_FILE="$ENV_EXAMPLE"
    echo -e "${YELLOW}Using example config: $ENV_EXAMPLE${NC}"
else
    echo -e "${RED}Error: Neither $ENV_FILE nor $ENV_EXAMPLE found.${NC}"
    exit 1
fi

# Extract port
PORT=$(get_value "$SOURCE_FILE" "port")
if [ -z "$PORT" ]; then
    echo -e "${YELLOW}Warning: Port not found in $SOURCE_FILE, using default 1080${NC}"
    PORT="1080"
fi

# Extract IP (optional, might be used in future)
IP=$(get_value "$SOURCE_FILE" "ip")

# Create root .env file
echo "# Generated by generate-compose-env.sh" > "$ROOT_ENV_FILE"
echo "# Do not edit manually; edit config/.env or config/.env.example instead" >> "$ROOT_ENV_FILE"
echo "SOCKS5_PORT=$PORT" >> "$ROOT_ENV_FILE"
if [ -n "$IP" ]; then
    echo "SOCKS5_IP=$IP" >> "$ROOT_ENV_FILE"
fi

echo -e "${GREEN}Generated $ROOT_ENV_FILE with SOCKS5_PORT=$PORT${NC}"
echo -e "${GREEN}You can now run docker-compose up${NC}"